services:
  postgres:
    image: postgres:15
    container_name: backend-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: backend
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres-init/:/docker-entrypoint-initdb.d/
